### ISSUE TITLE
How to use 4-way plot between separate group?

### ISSUE THREAD

**Issue by wajm** [btmonier/ggviseq#3]
Hi, I need help.
I have 2 sets of group.
(p21 [Ctl vs cKO] and p28 [Ctl vs cKO])
In this case how to use 4-way plot set-up?
vsFourWay(
    x = 'p21', y = 'p28', control = '???????????', data = df.deseq,
    d.factor = NULL, type = 'cuffdiff', padj = 0.05, x.lim = NULL,
    y.lim = NULL, lfc = NULL, legend = TRUE, title = TRUE, grid = TRUE
)

**Comment by btmonier** [comment]
Before I can assess your problem, could you give me some more background information about your experimental setup? I'm not sure what you mean by "(p21 [Ctl vs cKO] and p28 [Ctl vs cKO])"

**Comment by wajm** [comment]
Oh, I'm sorry.
I have two data sets. (p21 control vs p21 mutant and p28 control vs p28 mutant)
p21 and p28 means development stage (day21 and day28).
So I want to make 4-way plot (x-axis is p21 control vs mutant and y-axis is p28 control vs mutant).
Thanks.

**Comment by btmonier** [comment]
Thanks - I understand now. `vsFourWay()`'s functionality explicitly works only with *one* data set implemented as one of the three data set types (`DESeq2`, `edgeR`, or `cuffdiff` table outputs). Additionally, `vsFourWay()` works with 3 variables in one data set, hence, why there is a `x`, `y`, and `control` parameter. Both `x` and `y` variables are compared to *one* `control` variable. I believe with your data, other ViDGER functionalities where you compare only two variables may be more appropriate and faceted together as an A/B figure.
