### ISSUE TITLE
highlight error in vsScatterPlot

### ISSUE THREAD

**Issue by Tang-YH** [btmonier/ggviseq#8]
Hello,
I used vsScatterPlot to get a CPM plot:
`vsScatterPlot(x="WT", y="KO", data=dgeData, type="edger", highlight=DEG_list)
`
No matter what I put in the "highlight" argument, it always returned the the error "No IDs in highlight vector are present in data frame." But the genes are all present in the data. 
I checked the file vsScatterPlot.r, and in lines 179-181 it says:
```
else if (!all(highlight %in% dat$id)) {
      stop("No IDs in highlight vector are present in data frame.")
}
```
I also ran the code` !all(DEG_list %in% dgeData$genes)`, and it returned "FALSE". 
Could you help with this issue?

**Comment by btmonier** [comment]
Interesting. What do the gene IDs look like when you run `head(dgeData$genes)`? Also, what does the structure of your `DEG_list` look like (e.g. `str(DEG_list)`?

**Comment by Tang-YH** [comment]
This is the result of head(dgeData$genes):
```
                  Geneid               TxLength
ENSMUSG00000102693 "ENSMUSG00000102693" "1070"  
ENSMUSG00000064842 "ENSMUSG00000064842" "110"   
ENSMUSG00000051951 "ENSMUSG00000051951" "10444" 
ENSMUSG00000102851 "ENSMUSG00000102851" "480"   
ENSMUSG00000103377 "ENSMUSG00000103377" "2819"  
ENSMUSG00000104017 "ENSMUSG00000104017" "2233" 
```
The two columns are ensembl id and transcript length.
And `str(DEG_list)`:
`chr [1:278] "ENSMUSG00000102269" "ENSMUSG00000032769" ...`

**Comment by btmonier** [comment]
For your `dgeData$genes` `edgeR` slot, can you try with just a vector of the gene IDs (e.g. `c("ENSMUSG00000102693", "ENSMUSG00000064842", ...)`)? This has always been kind of tricky with `edgeR` classes since the `genes` slot is not specific with what type of data, headers, etc. go in there.

**Comment by Tang-YH** [comment]
Thank you so much! I replaced it with the gene IDs, and now it works perfectly.
